# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /export/kyukhin/tcl2lua/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /export/kyukhin/tcl2lua/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /export/kyukhin/tcl2lua/src/CMakeFiles /export/kyukhin/tcl2lua/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /export/kyukhin/tcl2lua/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tclparser

# Build rule for target.
tclparser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tclparser
.PHONY : tclparser

# fast build rule for target.
tclparser/fast:
	$(MAKE) -f CMakeFiles/tclparser.dir/build.make CMakeFiles/tclparser.dir/build
.PHONY : tclparser/fast

jim-format.o: jim-format.c.o
.PHONY : jim-format.o

# target to build an object file
jim-format.c.o:
	$(MAKE) -f CMakeFiles/tclparser.dir/build.make CMakeFiles/tclparser.dir/jim-format.c.o
.PHONY : jim-format.c.o

jim-format.i: jim-format.c.i
.PHONY : jim-format.i

# target to preprocess a source file
jim-format.c.i:
	$(MAKE) -f CMakeFiles/tclparser.dir/build.make CMakeFiles/tclparser.dir/jim-format.c.i
.PHONY : jim-format.c.i

jim-format.s: jim-format.c.s
.PHONY : jim-format.s

# target to generate assembly for a file
jim-format.c.s:
	$(MAKE) -f CMakeFiles/tclparser.dir/build.make CMakeFiles/tclparser.dir/jim-format.c.s
.PHONY : jim-format.c.s

tclparser.o: tclparser.c.o
.PHONY : tclparser.o

# target to build an object file
tclparser.c.o:
	$(MAKE) -f CMakeFiles/tclparser.dir/build.make CMakeFiles/tclparser.dir/tclparser.c.o
.PHONY : tclparser.c.o

tclparser.i: tclparser.c.i
.PHONY : tclparser.i

# target to preprocess a source file
tclparser.c.i:
	$(MAKE) -f CMakeFiles/tclparser.dir/build.make CMakeFiles/tclparser.dir/tclparser.c.i
.PHONY : tclparser.c.i

tclparser.s: tclparser.c.s
.PHONY : tclparser.s

# target to generate assembly for a file
tclparser.c.s:
	$(MAKE) -f CMakeFiles/tclparser.dir/build.make CMakeFiles/tclparser.dir/tclparser.c.s
.PHONY : tclparser.c.s

utf8.o: utf8.c.o
.PHONY : utf8.o

# target to build an object file
utf8.c.o:
	$(MAKE) -f CMakeFiles/tclparser.dir/build.make CMakeFiles/tclparser.dir/utf8.c.o
.PHONY : utf8.c.o

utf8.i: utf8.c.i
.PHONY : utf8.i

# target to preprocess a source file
utf8.c.i:
	$(MAKE) -f CMakeFiles/tclparser.dir/build.make CMakeFiles/tclparser.dir/utf8.c.i
.PHONY : utf8.c.i

utf8.s: utf8.c.s
.PHONY : utf8.s

# target to generate assembly for a file
utf8.c.s:
	$(MAKE) -f CMakeFiles/tclparser.dir/build.make CMakeFiles/tclparser.dir/utf8.c.s
.PHONY : utf8.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tclparser"
	@echo "... jim-format.o"
	@echo "... jim-format.i"
	@echo "... jim-format.s"
	@echo "... tclparser.o"
	@echo "... tclparser.i"
	@echo "... tclparser.s"
	@echo "... utf8.o"
	@echo "... utf8.i"
	@echo "... utf8.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

